# Site settings
title: Portfolio of student mn222zh
email: mn222zh@student.lnu.se
description: > # this means to ignore newlines until "baseurl:"
  Exam assignment - client-based webprogramming at Linnaeus university
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  mn222zh
paginate: 3

# Build settings
markdown: kramdown
